# DockerFile-MariaDB

# Using latest MariaDB https://hub.docker.com/_/mariadb 
FROM mariadb:latest

LABEL version="MariaDB-v1.0"
LABEL description="MariaDB Server - ProductJack"

# Install Packages
RUN apt-get update 
RUN apt-get install openssh-server openssh-client vim net-tools -y 
RUN echo "alias ll='ls -l'" >> ~/.bashrc
RUN mkdir /db/

# Passing Root Password to local .mycf
ARG DB_Root_Password
RUN echo "[client]\n"\
"user=root\n"\
"password=${DB_Root_Password}\n"\
>> ~/.my.cnf