# DockerFile-latest tag

# Use WordPress - latest
FROM wordpress:latest

LABEL version="WordPress Latest"
LABEL description="WordPress Latest Container"

# ARG USER
ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID} -ne 0 ] && [ ${GROUP_ID} -ne 0 ]; then \
    userdel -f www-data &&\
    if getent group www-data ; then groupdel www-data; fi &&\
    groupadd -g ${GROUP_ID} www-data &&\
    useradd -l -u ${USER_ID} -g www-data www-data &&\
	chown -R www-data:www-data /var/www/html \
;fi

RUN apt-get update && \
    apt-get upgrade -y 

