# DockerFile-MariaDB

# Use MySql 5.7 
FROM mysql:5.7.36

LABEL version="MySql Version 5.7"
LABEL description="MySql Local Server"

# Install Packages
RUN apt-get update 
RUN apt-get install openssh-server openssh-client vim net-tools -y 
RUN echo "alias ll='ls -l'" >> ~/.bashrc
RUN mkdir /db/

# Passing Root Password to local .mycf
ARG DB_Root_Password
RUN echo "[client]\n"\
"user=root\n"\
"password=${DB_Root_Password}\n"\
>> ~/.my.cnf

# COPY ./docker/database/MySql/init.sql /docker-entrypoint-initdb.d/
