# DockerFile-MariaDB

# Use MySql 5.7 
FROM mysql:5.7.36

LABEL version="MySql Version 5.7"
LABEL description="MySql Local Server"

# Adding GPG Keys
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29 

# Install Packages
RUN apt-get update && \
    apt-get install -y openssh-server openssh-client vim net-tools && \
    echo "alias ll='ls -l'" >> ~/.bashrc && \
    mkdir /db

# Passing Root Password to local ~/.my.cnf
ARG DB_Root_Password
RUN echo "[client]\n"\
"user=root\n"\
"password=${DB_Root_Password}\n"\
>> ~/.my.cnf

# COPY ./docker/database/MySql/init.sql /docker-entrypoint-initdb.d/