version: "3"
services:
  db:
    build: 
      context: .
      dockerfile: ./docker/${Database_DockerFile}
      args:
        DB_Root_Password: "${DB_Root_Password}"
    container_name: ${DB_Container}
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_Root_Password}"
      MYSQL_USER: "${DB_User}"
      MYSQL_PASSWORD: "${DB_User_Password}"
      MYSQL_DATABASE: "${DB_Database}"
    networks:
      - mylocal_nw  
    ports:
      - 3307:3306
    volumes:
     # - ${Project_Root}/docker/database/MariaDB/db_data:/var/lib/mysql
      - ./${DB_VolumePath}/${DB_Container}-${DB_Engine}:/var/lib/mysql  
      - ./conf.d:/etc/mysql/mysql.conf.d
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./${WP_DirPath}:/var/www/html 
    networks:
      - mylocal_nw
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "${DB_User}"
      WORDPRESS_DB_PASSWORD: "${DB_User_Password}"
      WORDPRESS_DB_NAME: "${DB_Database}"

networks:
  mylocal_nw: {} 