# Dockerfile-app
# PROJ_ROOT=/home/jerry/Docker/productjack/appcode/trunk/app
# buildContext: $(Build.Repository.LocalPath)

# Use PHP 5.6 with Apache for the base image
FROM php:5.6-apache

# Enable the Rewrite Apache mod
RUN cd /etc/apache2/mods-enabled && \
    ln -s ../mods-available/rewrite.load

# Install required PHP extensions
# -- GD
RUN apt-get update && \
    apt-get install -y libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ && \
    docker-php-ext-install -j$(nproc) gd
# -- MySql
RUN docker-php-ext-install -j$(nproc) mysql pdo_mysql
# -- Vim
RUN apt-get install -y vim
RUN echo "alias ll='ls -l'" >> ~/.bashrc

# ENV PROJ_ROOT="/home/jerry/Docker/ProductJack-ENVDOC/trunk" 
# WORKDIR ${PROJ_ROOT}

# Copy HTTP server config
COPY ./docker/apache/000-default.conf /etc/apache2/sites-available/

