# Image PHP 7.4 Apache
FROM php:7.4-apache

LABEL ImageName="PHP74-APache2"
LABEL Maintainer="jerrybopara@gmail.com"

# --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') - use this while building an image. 
ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE


# Enable the Rewrite Apache mod
RUN cd /etc/apache2/mods-enabled && \
    ln -s ../mods-available/rewrite.load

# Enabling the Mod SSL - 
RUN a2enmod ssl

# install the PHP extensions 
RUN set -ex; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y build-essential; \
	apt-get install -y --no-install-recommends \
		libfreetype6-dev \
		libjpeg-dev \
		libmagickwand-dev \
		libpng-dev \
		libwebp-dev \
		libzip-dev \
		libonig-dev \
		libxslt-dev \
	; \
	\
	docker-php-ext-configure gd \
		--with-freetype \
		--with-jpeg \
		--with-webp \
	; \
	docker-php-ext-install -j "$(nproc)" \
		bcmath \
		exif \
		mysqli \
		zip \
		intl \
		pdo_mysql \
		bz2 \
		mbstring \
		pdo_mysql \
		soap \
		sockets \
		xsl \
	;

# Install wget netstat etc
RUN apt-get install -y vim wget net-tools

# Installing mkcert - to generate self sign SSL Certificate's.
RUN apt-get install -y libnss3-tools
RUN echo "alias ll='ls -l'" >> ~/.bashrc
RUN mkdir /etc/apache2/ssl_certs

# Copying mkcert install script and setting up SSL/
COPY ./docker/install-ssl.sh /etc/apache2/ssl_certs/
RUN cd /etc/apache2/ssl_certs/ && chmod u+x install-ssl.sh && \
	./install-ssl.sh 

# Installing MongoDB
RUN pecl install mongodb \
&& docker-php-ext-enable mongodb

# Copy HTTP server config
# COPY ./docker/000-default.conf /etc/apache2/sites-available/

