# Use PHP 5.6 with Apache for the base image
FROM php:5.6-apache

LABEL ImageName="PHP74-APache2"
LABEL Maintainer="jerrybopara@gmail.com"

# --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') - use this while building an image. 
ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

# Enable the Rewrite Apache mod
RUN cd /etc/apache2/mods-enabled && \
    ln -s ../mods-available/rewrite.load

# Install required PHP extensions
# -- GD
RUN apt-get update && \
    apt-get install -y libfreetype6-dev && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ && \
    docker-php-ext-install -j$(nproc) gd
# -- MySql
RUN docker-php-ext-install -j$(nproc) mysql pdo_mysql
RUN apt-get install mongodb

# -- Vim
RUN apt-get install -y vim
RUN echo "alias ll='ls -l'" >> ~/.bashrc
RUN mkdir /etc/apache2/SSL_CERTS


# Copy HTTP server config
# COPY ./docker/000-default.conf /etc/apache2/sites-available/

